### ISSUE TITLE
Sass & Playground

### ISSUE THREAD

**Issue by xgqfrms** [xgqfrms/hui-cli#8]
# Sass & Playground
 
https://www.sassmeister.com/

```scss

    /* scss variables */
    $default-color: #000;
    /* mixin */
    @mixin common-lable($color) {
        color: $color;
        display: inline-block;
        width: 55px;
        text-align: center;
    }
    .audit-common-lable{
        @include common-lable($default-color);
        &::after{
            display: inline-block;
            content: ":";
        }
    }
    .audit-common-lable-placeholder{
        @include common-lable($default-color);
    }
    .audit-common-padding{
        display: block;
        padding-bottom: 5px;
        border: 0;
    }
    .audit-common-content{
        margin-top: 10px;
    }
    .audit-common-link,
    .audit-common-link:hover{
        color: #298DFF !important;
        text-decoration: none;
        cursor: pointer;
    }
    .audit-common-row-padding{
        margin-bottom: 5px;
    }

```

**Comment by xgqfrms** [comment]
```css

/* scss variables */
/* mixin */
.audit-common-lable {
  color: #000;
  display: inline-block;
  width: 55px;
  text-align: center;
}
.audit-common-lable::after {
  display: inline-block;
  content: ":";
}

.audit-common-lable-placeholder {
  color: #000;
  display: inline-block;
  width: 55px;
  text-align: center;
}

.audit-common-padding {
  display: block;
  padding-bottom: 5px;
  border: 0;
}

.audit-common-content {
  margin-top: 10px;
}

.audit-common-link,
.audit-common-link:hover {
  color: #298DFF !important;
  text-decoration: none;
  cursor: pointer;
}

.audit-common-row-padding {
  margin-bottom: 5px;
}

```
